/**
 * Second-tier illustration source: native Unicode emoji rendered as SVG
 * `<text>`. Used whenever a subject has no hand-drawn entry in `art.ts` —
 * gives real, relevant pictures for a much wider range of topics (space,
 * ocean, professions, weather, insects, extra animals, ...) with zero new
 * dependencies, no licensing to track, and no bundle-size cost (it's just
 * strings). Not palette-recolorable like the hand-drawn set, so it's only
 * used for non-outline book styles — see generateIllustrationSync().
 */
export const EMOJI_MAP: Record<string, string> = {
  // Animals
  lion: "🦁",
  giraffe: "🦒",
  sheep: "🐑",
  goat: "🐐",
  horse: "🐴",
  deer: "🦌",
  squirrel: "🐿️",
  camel: "🐫",
  duck: "🦆",
  goose: "🦢",
  turtle: "🐢",
  owl: "🦉",
  eagle: "🦅",
  bee: "🐝",
  dolphin: "🐬",
  whale: "🐳",
  shark: "🦈",
  octopus: "🐙",
  crab: "🦀",
  seal: "🦭",
  koala: "🐨",
  panda: "🐼",
  kangaroo: "🦘",
  hedgehog: "🦔",
  peacock: "🦚",
  parrot: "🦜",
  hippo: "🦛",
  rhino: "🦏",
  snake: "🐍",
  spider: "🕷️",
  ant: "🐜",
  mosquito: "🦟",
  worm: "🪱",
  // Space
  rocket: "🚀",
  planet: "🪐",
  astronaut: "🧑‍🚀",
  alien: "👽",
  ufo: "🛸",
  comet: "☄️",
  telescope: "🔭",
  // Weather
  rain: "🌧️",
  snow: "❄️",
  lightning: "⚡",
  rainbow: "🌈",
  snowman: "⛄",
  // Professions
  doctor: "🧑‍⚕️",
  teacher: "🧑‍🏫",
  police: "👮",
  firefighter: "🧑‍🚒",
  chef: "🧑‍🍳",
  farmer: "🧑‍🌾",
  pilot: "🧑‍✈️",
  scientist: "🧑‍🔬",
  // Fruits & vegetables
  coconut: "🥥",
  avocado: "🥑",
  potato: "🥔",
  tomato: "🍅",
  broccoli: "🥦",
  eggplant: "🍆",
  chili: "🌶️",
  garlic: "🧄",
  onion: "🧅",
  lemon: "🍋",
  kiwi: "🥝",
  peach: "🍑",
  pear: "🍐",
  blueberry: "🫐",
  // Food & drinks
  rice: "🍚",
  noodles: "🍜",
  satay: "🍢",
  milk: "🥛",
  honey: "🍯",
  coffee: "☕",
  tea: "🍵",
  donut: "🍩",
  cookie: "🍪",
  chocolate: "🍫",
  candy: "🍬",
  // Vehicles
  motorcycle: "🏍️",
  helicopter: "🚁",
  ship: "🚢",
  ambulance: "🚑",
  firetruck: "🚒",
  tractor: "🚜",
  scooter: "🛴",
  // Plants
  palmtree: "🌴",
  cactus: "🌵",
  sunflower: "🌻",
  rose: "🌹",
  // Music
  guitar: "🎸",
  drum: "🥁",
  piano: "🎹",
  violin: "🎻",
  // Sports
  soccer: "⚽",
  basketball: "🏀",
  swimming: "🏊",
  // School & everyday objects
  pencil: "✏️",
  backpack: "🎒",
  scissors: "✂️",
  ruler: "📏",
  crayon: "🖍️",
  paint: "🎨",
  phone: "📱",
  computer: "💻",
  lightbulb: "💡",
  tv: "📺",
  camera: "📷",
  // Islamic / Ramadan
  mosque: "🕌",
  prayerbeads: "📿",
  lantern: "🏮",
  // Body parts
  eye: "👁️",
  hand: "✋",
  foot: "🦶",
  ear: "👂",
  nose: "👃",
  mouth: "👄",
  tooth: "🦷",
};

/** Indonesian aliases → EMOJI_MAP keys. Longer/more specific phrases first, so substring matching doesn't shadow them with a shorter alias. */
const EMOJI_SYNONYMS: Record<string, string> = {
  "kuda nil": "hippo",
  "bawang putih": "garlic",
  "anjing laut": "seal",
  singa: "lion",
  jerapah: "giraffe",
  domba: "sheep",
  kambing: "goat",
  kuda: "horse",
  rusa: "deer",
  tupai: "squirrel",
  unta: "camel",
  bebek: "duck",
  angsa: "goose",
  "kura-kura": "turtle",
  "burung hantu": "owl",
  elang: "eagle",
  lebah: "bee",
  "lumba-lumba": "dolphin",
  paus: "whale",
  hiu: "shark",
  gurita: "octopus",
  kepiting: "crab",
  koala: "koala",
  kanguru: "kangaroo",
  landak: "hedgehog",
  merak: "peacock",
  kakatua: "parrot",
  badak: "rhino",
  ular: "snake",
  "laba-laba": "spider",
  semut: "ant",
  nyamuk: "mosquito",
  cacing: "worm",
  roket: "rocket",
  planet: "planet",
  astronot: "astronaut",
  komet: "comet",
  teleskop: "telescope",
  hujan: "rain",
  salju: "snow",
  petir: "lightning",
  pelangi: "rainbow",
  "manusia salju": "snowman",
  dokter: "doctor",
  guru: "teacher",
  polisi: "police",
  "pemadam kebakaran": "firefighter",
  koki: "chef",
  petani: "farmer",
  pilot: "pilot",
  ilmuwan: "scientist",
  perawat: "doctor",
  kelapa: "coconut",
  alpukat: "avocado",
  kentang: "potato",
  tomat: "tomato",
  brokoli: "broccoli",
  terong: "eggplant",
  cabai: "chili",
  cabe: "chili",
  bawang: "onion",
  persik: "peach",
  pir: "pear",
  nasi: "rice",
  mie: "noodles",
  sate: "satay",
  susu: "milk",
  madu: "honey",
  kopi: "coffee",
  teh: "tea",
  donat: "donut",
  cokelat: "chocolate",
  permen: "candy",
  motor: "motorcycle",
  helikopter: "helicopter",
  ambulans: "ambulance",
  traktor: "tractor",
  skuter: "scooter",
  "pohon palem": "palmtree",
  kaktus: "cactus",
  "bunga matahari": "sunflower",
  mawar: "rose",
  gitar: "guitar",
  biola: "violin",
  "sepak bola": "soccer",
  basket: "basketball",
  berenang: "swimming",
  pensil: "pencil",
  ransel: "backpack",
  gunting: "scissors",
  penggaris: "ruler",
  krayon: "crayon",
  melukis: "paint",
  telepon: "phone",
  komputer: "computer",
  lampu: "lightbulb",
  televisi: "tv",
  kamera: "camera",
  masjid: "mosque",
  tasbih: "prayerbeads",
  lentera: "lantern",
  mata: "eye",
  tangan: "hand",
  kaki: "foot",
  telinga: "ear",
  hidung: "nose",
  mulut: "mouth",
  gigi: "tooth",
};

export function resolveEmoji(subject: string): string | null {
  const slug = subject.toLowerCase().trim();
  if (EMOJI_MAP[slug]) return EMOJI_MAP[slug];
  for (const [alias, key] of Object.entries(EMOJI_SYNONYMS)) {
    if (slug.includes(alias) && EMOJI_MAP[key]) return EMOJI_MAP[key];
  }
  for (const key of Object.keys(EMOJI_MAP)) {
    if (slug.includes(key)) return EMOJI_MAP[key];
  }
  return null;
}
