import type { Book, BookConfig } from "@/types";
import { generateFullBook } from "@/lib/ai/generate-book";

export const SAMPLE_BOOK_CONFIG: BookConfig = {
  bookType: "workbook",
  topic: "Mengenal huruf A-Z untuk anak usia 3-5 tahun",
  ageRange: "3-5",
  language: "id",
  numPages: 30,
  difficulty: "easy",
  style: "cute-cartoon",
  activities: ["tracing", "letter-recognition", "counting", "coloring", "matching", "cut-paste", "find-circle"],
  aiSelectActivities: false,
  additionalInstructions: "Gunakan karakter hewan yang lucu dan bahasa yang sederhana untuk anak prasekolah.",
};

let cached: Book | null = null;

/** Deterministic built-in demo book — "ABC Workbook", 30 pages, generated by the mock AI pipeline. */
export function getSampleBook(): Book {
  if (!cached) {
    cached = generateFullBook(SAMPLE_BOOK_CONFIG, "demo-user");
    cached.id = "sample-abc-workbook";
    cached.title = "ABC Workbook";
    cached.pages[0].title = "ABC Workbook";
    if (cached.pages[0].data.type === "cover") {
      cached.pages[0].data.subtitle = "Usia 3-5 tahun";
    }
  }
  return cached;
}
